name: Build and Upload to App Store

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'package.json'
      - 'android/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_ACCESS_TOKEN }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build APK for Production
        run: EXPO_TOKEN=${{ secrets.EXPO_ACCESS_TOKEN }} eas build --platform ios --profile production --non-interactive

      - name: Submit to Google Play
        run: EXPO_TOKEN=${{ secrets.EXPO_ACCESS_TOKEN }} eas submit --platform ios --profile production --latest --non-interactive
